name: Build and Test

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NUGET_TOKEN:  ${{secrets.NUGET_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
      
  semantic_release:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/exec@3.3.8
            @semantic-release/changelog@3.0.0
    outputs:
      new_release_version: ${{ steps.semantic_release.outputs.new_release_version }}
            
  nuget:
    needs: [semantic_release]
    runs-on: ubuntu-latest
    
    steps:
      - name: debug
        run: echo ${{ needs.semantic_release.outputs.new_release_version }}
      - name: build
        run: dotnet build --configuration Release -p:Version=${{ needs.semantic_release.outputs.new_release_version }}
      - name: pack
        run: dotnet pack --configuration Release --output ./artifacts -p:PackageVersion=${{ needs.semantic_release.outputs.new_release_version }}
      - name: push
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${ NUGET_TOKEN } --source https://api.nuget.org/v3/index.json
