name: Build and Test

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NUGET_TOKEN:  ${{secrets.NUGET_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
      
  publish:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/exec@3.3.8
            @semantic-release/changelog@3.0.0
            
  nuget:
    needs: [publish]
    runs-on: ubuntu-latest
    
    steps:
      - name: build
        run: dotnet build --configuration Release -p:Version=${nextRelease.version}
      - name: pack
        run: dotnet pack --configuration Release --output ./artifacts -p:PackageVersion=${nextRelease.version}
      - name: push
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${ NUGET_TOKEN } --source https://api.nuget.org/v3/index.json
