name: Build and Test

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NUGET_TOKEN:  ${{secrets.NUGET_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
      
  semantic_release_and_nuget_publish:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/exec@3.3.8
            @semantic-release/changelog@3.0.0      
      - name: Nuget build, pack and push..
        run: dotnet build --configuration Release -p:Version=${{ steps.semantic.outputs.new_release_version }}
